### ISSUE TITLE
Connecting multiple peers

### ISSUE THREAD

**Issue by GitOlli** [lsalzman/enet#169]
Hello! I'm making a game with ENet and sfml. I have been testing around with ENet and i was wondering what is the correct way to connect multiple peers from a single ENet client? I have tried many different configurations but the peers don't seem to connect. I didn't find anything related to this.

**Comment by bjorn** [comment]
* When you create the host with `enet_host_create`, make sure to pass in a high enough `peerCount` to allow for multiple connections.
* Then just issue multiple calls to `enet_host_connect` to connect the host to multiple foreign hosts, creating multiple peers. 
* Finally make sure to keep servicing the host with `enet_host_service`, otherwise it can't initiate the connections.

**Comment by GitOlli** [comment]
Do i need to have different ENetAddresses for each peer?

**Comment by bjorn** [comment]
> Do i need to have different ENetAddresses for each peer?

No, that struct is only used by `enet_host_connect` during its call, and can be reused for another call afterwards. Normally you'd allocate it on the stack.
