### ISSUE TITLE
Are packets compressed once?

### ISSUE THREAD

**Issue by playingoDEERUX** [lsalzman/enet#193]
Hello, I want to ask an important question about enet's range coder / compression.
Does ENet only compress packets on enet_packet_create, or on every packet flush within enet_host_service which holds the queued packets using enet_peer_send, and does it compress for every peer packets are being sent to?

Thanks in regards, I hope the question is easy to understand as it would concern the effiency of ENet.

**Comment by bjorn** [comment]
> Does ENet only compress packets on enet_packet_create, or on every packet flush within enet_host_service which holds the queued packets using enet_peer_send

So, compression happens in `enet_protocol_send_outgoing_commands`:

https://github.com/lsalzman/enet/blob/cf735e639e5c9e3d2d84d71f1dbf789e8c2f3fd0/protocol.c#L1653-L1658

Since it happens after calling `enet_protocol_check_outgoing_commands`, it seems to me like it first sets up all the buffers for sending, then compresses and then sends with `enet_socket_send`. That would imply, that when a reliable packet needs to be sent again, its data will also be compressed again.

> and does it compress for every peer packets are being sent to?

Looks like it to me, but I'd suggest to try following the code yourself as well. :-)
