### ISSUE TITLE
Round trip time varies with update rate

### ISSUE THREAD

**Issue by xissburg** [lsalzman/enet#194]
Consider the following: if `enet_host_service` is called once every second (in a while loop, as usual) in one end while the other end is producing packets every 100ms, with no network jitter, the `enet_host_service` loop should run 10 times thus consuming 10 packets. In the receiving end, it looks as if all packets had arrived at the same time, but on a system level, they have all arrived within 100ms of one another. Do the system calls and structures provide any information about the time a packet arrived? This information is important when measuring relative time quantities such as RTT and synchronizing clocks. Is the only solution to call `enet_host_service` at a higher rate or even have a dedicated networking thread which calls `enet_host_service` with no timeout, thus processing incoming packets as quickly as possible?

The issue described above seems to be the reason why `ENetPeer::roundTripTime` decreases as the client and server update rates go up (e.g. disabling vsync on the client). If a ping packet arrives right after the `enet_host_service` loop is done, it will only be processed in the next update (e.g. 16ms later) and the pong will be sent back with a significant delay, thus causing the RTT calculations to be imprecise. At the same time, if the ping packet arrives when `enet_host_service` is called, the pong with be sent immediately. If the client and server are running on the same machine, it looks like you'd have ping-pong sequences that take 16ms while the next one takes near 0ms, thus resulting in large variance.

**Comment by lsalzman** [comment]
Calling enet_host_service once a second won't work well at all. Ideally, it's meant to be called every frame within a game loop.

**Comment by xissburg** [comment]
Calling it once a second was just a contrived example to illustrate my point. Just use a smaller number and it will be the same.

**Comment by lsalzman** [comment]
For game usage it is adequate to just call it at your game framerate, i.e. 30-60 HZ or similar.

**Comment by xissburg** [comment]
I know that, and it looks like you did not read my question at all. I am asking about the precise calculation of the time a packet has arrived.

**Comment by lsalzman** [comment]
I don't believe you can get timing information from the recvmsg syscall. Your best bet is to call it as often as possible. That's how it's designed to work. It is understood that if you don't call it often you will see corresponding granularity effects in the RTT since the timing of everything is determined by how often you call it.

**Comment by mman** [comment]
Hi Lee,

I think I may have seen a similar issue as the original poster, which relates to how is the PL and RTT computed when the peer connection breaks and we start loosing reliable/unreliable/ping packets.

During that window when the packets are starting to be lost the RTT and PL values represent the last “good” values and do not indicate that there is a problem with the peer. And that lasts for 15/30 seconds depending on your timeout configuration until the peer is eventually disconnected. And from my experience it does not matter how often you call enet_host_service. Is my understanding correct?

I think (but I may be mistaken as I do not known the code well) this is because the PL and RTT are recomputed only when the ping or reliable packet is received?

My expectation as a user of the library would be that PL and RTT should start increasing with every tick of enet_host_service when a peer becomes dead, but not yet disconnected.

Imagine kids playing a game, where one peer will timeout, but for others still looks as alive (good RTT and PL values) despite being dead and despite the fact that it will disconnect in say 15 seconds.

So the solution could be to recompute PLL and RTT on every enet_host_service taking into account “expected” incoming pings from the peer and properly indicate that PL and RTT are increasing should the expected ping packets be missing.

Do I understand it right?
Martin
